import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.11.1/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.AppKt"
}

val printPythonPathTaskProvider = tasks.register<Exec>("printPythonPath") {
    doFirst { println("Absolute python path:") }
    commandLine("which", "python3.11")
    doLast { println("") }
}

val printGradleDaemonEnvsTaskProvider = tasks.register<Exec>("printGradleDaemonEnvs") {
    val daemonPid = ProcessHandle.current().pid()

    doFirst {
        println("Environment variables for Gradle Daemon with pid = $daemonPid")
    }
    commandLine("ps", "eww", "$daemonPid")
    dependsOn(printPythonPathTaskProvider)
    doLast { println("") }
}

val somePythonWorkTaskProvider = tasks.register<Exec>("somePythonWork") {
    commandLine("python3.11", "--version")

    doFirst {
        println("Environment variables from System.getenv:")

        System
            .getenv()
            .entries
            .joinToString(
                separator = System.lineSeparator(),
                transform = { "${it.key} = ${it.value}" }
            )
            .let(::println)
            .let { println("") }
    }

    dependsOn(printGradleDaemonEnvsTaskProvider)
}

tasks.withType<KotlinCompile>().configureEach {
    dependsOn(somePythonWorkTaskProvider)
}
